### ISSUE TITLE
cannot npm install heimcontrol.js

### ISSUE THREAD

**Issue by TexRx** [ni-c/heimcontrol.js#104]
Has anyone actually built this lately? I've followed the instructions, and I've tried multiple times, and each time I get an error running npm install. I am using Node 0.10.32 / npm 1.4.28. I've run `npm instal`l w/ and w/o `sudo`.

The first warning message I receive after running `npm install` is

```
npm WARN excluding symbolic link src/du.ino -> duino/duino.ino
```

Then I receive

```
> serialport@1.4.6 install /home/tobino/heimcontrol.js/node_modules/duino/node_modules/serialport
> node-pre-gyp install --fallback-to-build
```

Then I receive a really long error message related to node-gyp (sorry for the long paste):

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: node-v0.10.32.tar.gz local checksum 7774bc5b9e61b040f653ee5a6b58c7cf4c065729501655deb0d35ec941c0eb46 not match remote c2120d0e3d2d191654cb11dbc0a33a7216d537
32173317681da9502be0030f10
gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:299:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:340:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:943:16
gyp ERR! stack     at process._tickCallback (node.js:419:13)
gyp ERR! System Linux 3.12.29+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=serialport" "--configuration=Release" "--module_n
ame=serialport" "--version=1.4.6" "--major=1" "--minor=4" "--patch=6" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=arm" "--target_a
rch=arm" "--module_main=./serialport" "--host=https://node-serialport.s3.amazonaws.com/" "--module_path=/home/tobino/heimcontrol.js/node_modules/duino/node_modules/serialport/bui
ld/serialport/v1.4.6/Release/node-v11-linux-arm" "--remote_path=./serialport/v1.4.6/Release/" "--package_name=node-v11-linux-arm.tar.gz" "--staged_tarball=build/stage/serialport/
v1.4.6/Release/node-v11-linux-arm.tar.gz" "--hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.4.6/Release/" "--hosted_tarball=https://node-serialport.s3.amazona
ws.com/serialport/v1.4.6/Release/node-v11-linux-arm.tar.gz"
gyp ERR! cwd /home/tobino/heimcontrol.js/node_modules/duino/node_modules/serialport
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.4.6 --major=1 --mino$=4 --patch=6 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./serialport --host=https://node-serialport.s$.amazonaws.com/ --module_path=/home/tobino/heimcontrol.js/node_modules/duino/node_modules/serialport/build/serialport/v1.4.6/Release/node-v11-linux-arm --remote_path=./serialpor$/v1.4.6/Release/ --package_name=node-v11-linux-arm.tar.gz --staged_tarball=build/stage/serialport/v1.4.6/Release/node-v11-linux-arm.tar.gz --hosted_path=https://node-serialport.$3.amazonaws.com/serialport/v1.4.6/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.4.6/Release/node-v11-linux-arm.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/tobino/heimcontrol.js/node_modules/duino/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:76:$9)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:756:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
node-pre-gyp ERR! System Linux 3.12.29+
node-pre-gyp ERR! command "node" "/home/tobino/heimcontrol.js/node_modules/duino/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/tobino/heimcontrol.js/node_modules/duino/node_modules/serialport
node-pre-gyp ERR! node -v v0.10.32
node-pre-gyp ERR! node-pre-gyp -v v0.5.19
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.4.6 --major=1 --minor=4 --patch=6 --runtime=node --n
ode_abi=node-v11 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=/
home/tobino/heimcontrol.js/node_modules/duino/node_modules/serialport/build/serialport/v1.4.6/Release/node-v11-linux-arm --remote_path=./serialport/v1.4.6/Release/ --package_name
=node-v11-linux-arm.tar.gz --staged_tarball=build/stage/serialport/v1.4.6/Release/node-v11-linux-arm.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.4
.6/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.4.6/Release/node-v11-linux-arm.tar.gz' (1)

npm ERR! serialport@1.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@1.4.6 install script.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.12.29+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/tobino/heimcontrol.js
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

I've looked up the relevant dependency repos and I don't see any reported issues relevant to the issues that I see during install. Any ideas?

**Comment by kristianenge** [comment]
Hi, 
I have tried to install heimcontrol.js multiple times on Raspbian but I can`t get passed the 'npm install' step.

Error:
make: Entering directory '/home/pi/heimcontrol.js/node_modules/piswitch/node_modules/wiring-pi/build'
  CXX(target) Release/obj.target/wiringPi/src/bindings.o
../src/bindings.cc: In function ‘v8::Handle<v8::Value> wpi::piBoardId(const v8::Arguments&)’:
../src/bindings.cc:660:44: error: cannot convert ‘char**’ to ‘int*’ for argument ‘4’ to ‘void piBoardId(int*, int*, int*, int*, int*)’
wiringPi.target.mk:84: recipe for target 'Release/obj.target/wiringPi/src/bindings.o' failed
make: *** [Release/obj.target/wiringPi/src/bindings.o] Error 1
make: Leaving directory '/home/pi/heimcontrol.js/node_modules/piswitch/node_modules/wiring-pi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 3.12.35+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/heimcontrol.js/node_modules/piswitch/node_modules/wiring-pi
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm ERR! wiring-pi@1.1.2 install: `/bin/bash ./install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wiring-pi@1.1.2 install script.
npm ERR! This is most likely a problem with the wiring-pi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     /bin/bash ./install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls wiring-pi
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.12.35+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/pi/heimcontrol.js
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/heimcontrol.js/npm-debug.log
npm ERR! not ok code 0

Should I try installing on ArchLinux instead?

**Comment by tjanson** [comment]
@kristianenge I think this issue is not related to Raspbian/Arch/npm; wiring-pi is not compiling, which is a dependency of my PiSwitch plugin.

One workaround would be to delete the folder `plugins/piswitch` and the line [`"piswitch": "^1.0.3"`](https://github.com/ni-c/heimcontrol.js/blob/master/package.json#L28) — assuming you don’t need the 433 MHz remote functionality.

Other options are trying to fix the error in the source, or switching to `wiring-pi v2`. I’ll try to look into this when I have some time. You could also [file an issue with wiring-pi](https://github.com/eugeneware/wiring-pi/issues) and have them take a look.

**Comment by kristianenge** [comment]
@tjanson Thank you for the fast response. The workaround got me passed the error as you predicted.

I will file an issue with wiring-pi .

I cannot find the wiring-pi v2 repo, but maybe it isn`t released yet?

**Comment by tjanson** [comment]
> I cannot find the wiring-pi v2 repo, but maybe it isn`t released yet?

It’s not a separate repo, it’s just [the regular one](
https://github.com/eugeneware/wiring-pi) [[npm](
https://www.npmjs.com/package/wiring-pi) ]– v2 was published a few days
ago. You can test whether it works for you by trying `npm install
wiring-pi`. If it works and it’s compatible (I’d need to look into this), I
could update the dependency.

**Comment by jimmy01** [comment]
Spent many hours yesterday on this and encountered the exact same issue, won't post any error messages as they are pretty much the same as already posted, in the end I managed to install v2 manually and then forced v2 into the heimcontrol.js directory and managed to get it past the install process without errors, but fell over at run time it started looking for 1.1.2 again. Is there a way we can alter the dependency locally so it looks for 2.0 instead of 1.1.2 for now? I know it's possible to have further compatibility issues doing this without investigating the new package more thoroughly, but a big part of what I'm trying to do revolves around 433mhz controllers.

**Comment by beniroquai** [comment]
Same Issue here. Is there any update about this issue so far?

**Comment by tjanson** [comment]
Can you try the following for me: Increase the version number in [line 28 of `package.json`](https://github.com/ni-c/heimcontrol.js/blob/master/package.json#L28) to this:

```
    "piswitch": "^1.2.3"
```

Then `npm install`. This will use wiring-pi v2.0.0 — I haven’t tested it, but it might work.
Sorry for not supporting this better, I don’t have much time at the moment. If it still fails, remove PiSwitch from heimcontrol, like I said here:

> One workaround would be to delete the folder `plugins/piswitch` and the line `"piswitch": "^1.0.3"` — assuming you don’t need the 433 MHz remote functionality.

**Comment by beniroquai** [comment]
Actually it didn't help. I installed mongopi and node via the precompiled repositories. Could that be an issue?

**Comment by ewgor** [comment]
Did anyone tried this application using nodejs installed on a laptop running windows 7? I'm asking because I tried and I got a lot of errors I don't understand.
