### ISSUE TITLE
Fails to load ds18x20

### ISSUE THREAD

**Issue by paulTSB** [ni-c/heimcontrol.js#122]
Hi,
When I start heimcontrol.js I get the following message:

Failed to load c++ bson extension, using pure JS version
   info  - socket.io started
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
heimcontrol.js listening on port 8080
/home/pi/homecontrol/heimcontrol.js/node_modules/requirejs/bin/r.js:378
        throw err;
              ^
Error: Tried loading "ds18x20" at /home/pi/homecontrol/heimcontrol.js/ds18x20.js then tried node's require("ds18x20") and it failed with error: Error: Cannot find module './build/Release/shell'
    at /home/pi/homecontrol/heimcontrol.js/node_modules/requirejs/bin/r.js:2512:27
    at Object.context.execCb (/home/pi/homecontrol/heimcontrol.js/node_modules/requirejs/bin/r.js:1876:33)
    at Object.Module.check (/home/pi/homecontrol/heimcontrol.js/node_modules/requirejs/bin/r.js:1110:51)
    at Object.Module.enable (/home/pi/homecontrol/heimcontrol.js/node_modules/requirejs/bin/r.js:1381:22)
    at Object.Module.init (/home/pi/homecontrol/heimcontrol.js/node_modules/requirejs/bin/r.js:1018:26)
    at callGetModule (/home/pi/homecontrol/heimcontrol.js/node_modules/requirejs/bin/r.js:1408:63)
    at Object.context.completeLoad (/home/pi/homecontrol/heimcontrol.js/node_modules/requirejs/bin/r.js:1770:21)
    at Function.req.load (/home/pi/homecontrol/heimcontrol.js/node_modules/requirejs/bin/r.js:2525:17)
    at Object.context.load (/home/pi/homecontrol/heimcontrol.js/node_modules/requirejs/bin/r.js:1865:21)
    at Object.Module.load (/home/pi/homecontrol/heimcontrol.js/node_modules/requirejs/bin/r.js:1064:29)

I checked to see is the ds18x20 was in my  node_modules folder and it was.
I tried to run it again with the same result.
I tried to recompile ds18x0 with " npm install ds18x20" and got the following output:

> execSync@1.0.2 install /home/pi/homecontrol/heimcontrol.js/node_modules/ds18x20/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!
ds18x20@0.1.1 node_modules/ds18x20
├── sandal@1.0.1
├── async@0.2.10
└── execSync@1.0.2 (temp@0.5.1)

Same result. I also ran "npm install" but I'm still no further along.

**Comment by ni-c** [comment]
Hi, 

Sounds like a problem with the ds18x20 plugin: https://github.com/ni-c/heimcontrol.js/pull/120

Can you try to delete the `plugins/ds18x20/` directory?

EDIT:

> Cannot find module './build/Release/shell'

Seems to be a problem with the execSync module: https://github.com/mgutz/execSync/issues/27
