### ISSUE TITLE
socket.io error on startup (fresh install)

### ISSUE THREAD

**Issue by craigbloodworth** [ni-c/heimcontrol.js#139]
Failed to load c++ bson extension, using pure JS version
/home/craig/heimcontrol.js/node_modules/requirejs/bin/r.js:378
        throw err;
        ^

Error: Tried loading "socket.io" at /home/craig/heimcontrol.js/socket.io.js then tried node's require("socket.io") and it failed with error: TypeError: Cannot read property 'prototype' of undefined
    at /home/craig/heimcontrol.js/node_modules/requirejs/bin/r.js:2512:27
    at Object.execCb (/home/craig/heimcontrol.js/node_modules/requirejs/bin/r.js:1876:33)
    at Module.check (/home/craig/heimcontrol.js/node_modules/requirejs/bin/r.js:1110:51)
    at Module.enable (/home/craig/heimcontrol.js/node_modules/requirejs/bin/r.js:1381:22)
    at Module.init (/home/craig/heimcontrol.js/node_modules/requirejs/bin/r.js:1018:26)
    at callGetModule (/home/craig/heimcontrol.js/node_modules/requirejs/bin/r.js:1408:63)
    at Object.completeLoad (/home/craig/heimcontrol.js/node_modules/requirejs/bin/r.js:1770:21)
    at Function.req.load (/home/craig/heimcontrol.js/node_modules/requirejs/bin/r.js:2525:17)
    at Object.load (/home/craig/heimcontrol.js/node_modules/requirejs/bin/r.js:1865:21)
    at Module.load (/home/craig/heimcontrol.js/node_modules/requirejs/bin/r.js:1064:29)

**Comment by straris** [comment]
same issue here..
